export const COMPANY = {
  name: 'VANHSYA',
  tagline: 'Global Migration Platform',
  phoneE164: '+971522338785',
  phoneDisplay: '+971 52 233 8785',
  whatsappE164: '+971522338785',
  whatsappLink: 'https://wa.me/971522338785',
  emails: {
    founder: 'founder@vanhsya.com',
    career: 'career@vanhsya.com',
    connect: 'connect@vanhsya.com',
    hr: 'hr@vanhsya.com',
    support: 'support@vanhsya.com',
  },
  social: {
    facebook: 'https://facebook.com/vanhsyaglobal',
    instagram: 'https://instagram.com/vanhsyaglobal',
    linkedin: 'https://linkedin.com/company/vanhsya-global',
    twitter: 'https://twitter.com/vanhsya_global',
    youtubeChannel: 'https://www.youtube.com/@Vanhsya_live',
    youtubeSubscribe: 'https://www.youtube.com/@Vanhsya_live?sub_confirmation=1',
    youtubeChannelId: 'UC1IYTDYDon9VMznD0YgHijw',
  },
  uae: {
    country: 'United Arab Emirates',
    emirates: [
      'Abu Dhabi',
      'Dubai',
      'Sharjah',
      'Ajman',
      'Umm Al Quwain',
      'Ras Al Khaimah',
      'Fujairah',
    ],
    availability: '24/7 Support',
    partnershipLabel: 'UAE Partnerships & Credentials',
    partnershipNote: 'Credentials available on request',
  },
} as const;
